.github/workflows/pr.yml
Add github action for compilation on pull request to make checks
Closes: #11
=> Add github action on PR

dhall/static.dhall, src/expectation/model.rs, src/main.rs, src/mock.rs
Implement a matcher between incoming http request and registered expectation.
=> request matcher

Cargo.lock, Cargo.toml, dhall/Mock/package.dhall, dhall/static.dhall, src/expectation/model.rs, src/main.rs, src/web.rs
Add a web server on run to serve custom responses based on configuration loaded at the begining of the program
Crate : [hyper](https://github.com/hyperium/hyper)
Closes : #7 
Closes: #23
=> Web server integration

.github/workflows/master.yml
add github action on master for building
=> feat: add github action on master for building

Cargo.lock, Cargo.toml, src/lib.rs, tests/api_tests.rs
Add integration test module.
See: #20
=> test: Add integration tests.

.pre-commit-config.yaml
Add configuration for the tool [pre-commit](https://pre-commit.com/) to add checks before commit
=> feat: Add configuration for pre-commit

.github/workflows/pr.yml, Cargo.lock, Cargo.toml, src/bin/main.rs, src/cli.rs, src/expectation/model.rs, src/lib.rs, src/web.rs, tests/api_tests.rs
Expose a web api on another port to provide current mock configuration and so.
See:  #34
=> Add admin server endpoint

dev.nix
Add nix configuration file for `nix-shell` for development
Closes: #52
=> feat: Add nix for development environment

src/mock/model.rs, src/mock/service.rs, src/web/mock.rs
This merge request add filtering on Textual/JSON body. 
See: #61
=> Add body filtering

.github/workflows/pr.yml, Cargo.lock, Cargo.toml, tests/api_tests.rs
=> 44 - generate port

src/mock/model.rs, src/web/mock.rs
Filter incoming request with header configuration.
See: #61
=> feat: support header filtering.

.github/workflows/release.yml, Cargo.lock, Cargo.toml
Add new workflow on tag push to build bnary release and create a draft release on Github asociated
Rel: #51
=> Add release automation using github action

Cargo.lock, Cargo.toml, src/bin/main.rs, src/lib.rs, src/mock/model.rs, src/web/mock.rs, tests/api_tests.rs
Support query params filtering.
See: #61
=> Add query filtering

src/mock/model.rs
Improve matching strategy.
See: #66
=> Improve matching strategy

README.md
Add new content on README.md
- Why the project
- Usage
- Install
- Build
- ... 
Fixes : #16 
Go to [branch](https://github.com/dhall-mock/dhall-mock/tree/feat/16_README_improvment) to have a better vision of the result
Please review wording and make suggestions :pray:
=> Improvment README.md

src/bin/main.rs, src/mock/service.rs, src/web/admin.rs, tests/api_tests.rs
Change structopt cli, configuration file is not required
Fixes: #73
=> Configuration files optionals in cli

Cargo.lock, Cargo.toml, src/bin/main.rs, src/lib.rs, src/web/admin.rs, src/web/mock.rs, src/web/mod.rs, src/web/utils.rs, tests/api_tests.rs
remove "sigint" channel :recycle: 
use tokio::signal :sparkler: 
fix shutdown panic with runtime handler :rocket:
=> 74_improve_app_runtime

Cargo.lock
=> chore: Update deps

Cargo.lock
=> chore: Update dep versions

.github/workflows/release.yml
Add windows cross compilation for release
Closes: #58
=> Windows cross compilation for release
